# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.common import InvalidSelectorException, NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLoginingresoHappy():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def test_loginingresoHappy(self):
    # Test name: Login ingreso Happy
    # Step # | name | target | value
    # 1 | open | https://atlanticcity.pre.tecnalis.com/ |
    self.driver.get("https://atlantic:viQ[3UJ*Rk*Q1zC@atlanticcity.pre.tecnalis.com/")

    self.driver.maximize_window()
    # 3 | click | css=.d-xl-block > .btn-casino |
    # LOGIN
    # Test name: Login ingreso Happy
    # Step # | name | target | value
    # 1 | open | https://atlanticcity.pre.tecnalis.com/ |

    # 3 | click | css=.d-xl-block > .btn-casino |
    header = self.driver.find_element(By.CSS_SELECTOR, "header")
    buttons = header.find_elements(By.CSS_SELECTOR, "a")
    for button in buttons:
      if button.text == "INGRESAR":
        button.click()
        time.sleep(5)
    # self.driver.find_element(By.CSS_SELECTOR, ".d-xl-block > .btn-casino").click()
    # 4 click to casino online
    wait = WebDriverWait(self.driver, 60)
    target_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".cardDondeVamosSports > button")))
    target_button.click()
    # time.sleep(10)
    # 5 | type | id=username_aside | Testjordan01
    self.driver.find_element(By.ID, "username_aside").send_keys("Testjordan01")
    self.driver.find_element(By.ID, "password_aside").send_keys("Testjordan01")
    time.sleep(2)
    # 6| click | linkText=INGRESAR |
    self.driver.find_element(By.ID, "login_button_aside").click()
    time.sleep(10)

    #7 Menu

    sodesktop = self.driver.find_element(By.CSS_SELECTOR, ".show-only--desktop")
    menubutton = sodesktop.find_elements(By.CSS_SELECTOR, "a")
    for buttonmen in menubutton:
      if buttonmen.text == "menu":

        buttonmen.click()

    #8 Promociones


    aside = self.driver.find_element(By.CSS_SELECTOR, ".o-aside.fixed-left")
    prombuttons = aside.find_elements(By.CSS_SELECTOR, "a")

    for prmobutton in prombuttons:
      if prmobutton.accessible_name == "PROMOCIONES":
        prmobutton.click()

        # Bajar cursor
    #self.driver.execute_script("window.scrollTo(0,600)")
    #self.vars["window_handles"] = self.driver.window_handles
    #Seleccioar  ID DE JUGADOR
    #btn_container = self.driver.find_element(By.ID, "contentModalPlayerOculto")
    #btn_oculto = btn_container.find_element(By.CSS_SELECTOR, "button")
    #btn_oculto.click()
    # 7 | type | id=idAliraCampo | 850
    #self.driver.find_element(By.ID, "idAliraCampo").send_keys("850")
    # 8 | click | css=button:nth-child(4) |
    #self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 9 | mouseOver | css=.item-prev > button |

  
test_login_ingreso_happy = TestLoginingresoHappy()