# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTorneoruleta():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_torneoruleta(self):
    # Test name: torneo_ruleta
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://revamp.casinoatlanticcity.com/")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | linkText=INGRESAR | 
    self.driver.find_element(By.LINK_TEXT, "INGRESAR").click()
    # 4 | mouseOver | linkText=INGRESAR | 
    element = self.driver.find_element(By.LINK_TEXT, "INGRESAR")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseOut | linkText=INGRESAR | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 6 | click | css=.d-xl-block > .btn-casino | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-xl-block > .btn-casino").click()
    # 7 | type | id=username_aside | Testing16
    self.driver.find_element(By.ID, "username_aside").send_keys("Testing16")
    # 8 | type | id=password_aside | Testing16
    self.driver.find_element(By.ID, "password_aside").send_keys("Testing16")
    # 9 | click | id=login_button_aside | 
    self.driver.find_element(By.ID, "login_button_aside").click()
    # 10 | click | id=idAliraCampo | 
    self.driver.find_element(By.ID, "idAliraCampo").click()
    # 11 | type | id=idAliraCampo | 43393
    self.driver.find_element(By.ID, "idAliraCampo").send_keys("43393")
    # 12 | click | linkText=Cambiar id alira | 
    self.driver.find_element(By.LINK_TEXT, "Cambiar id alira").click()
  
