# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIngreso():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ingreso(self):
    # Test name: ingreso
    # Step # | name | target | value
    # 1 | open | https://atlanticcity.pre.tecnalis.com/ | 
    self.driver.get("https://atlanticcity.pre.tecnalis.com/")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | linkText=INGRESAR | 
    self.driver.find_element(By.LINK_TEXT, "INGRESAR").click()
    # 4 | mouseOver | linkText=INGRESAR | 
    element = self.driver.find_element(By.LINK_TEXT, "INGRESAR")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseOut | linkText=INGRESAR | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 6 | click | css=.d-xl-block > .btn-casino | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-xl-block > .btn-casino").click()
    # 7 | type | id=username_aside | Nvalencia
    self.driver.find_element(By.ID, "username_aside").send_keys("Nvalencia")
    # 8 | type | id=password_aside | Fari2021
    self.driver.find_element(By.ID, "password_aside").send_keys("Fari2021")
    # 9 | click | id=login_button_aside | 
    self.driver.find_element(By.ID, "login_button_aside").click()
    # 10 | click | css=.withoutline | 
    self.driver.find_element(By.CSS_SELECTOR, ".withoutline").click()
    # 11 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 12 | click | linkText=CERRAR SESIÓN | 
    self.driver.find_element(By.LINK_TEXT, "CERRAR SESIÓN").click()
  
