# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIngresonook():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ingresonook(self):
    # Test name: ingreso no ok
    # Step # | name | target | value
    # 1 | open | https://atlanticcity.pre.tecnalis.com/ | 
    self.driver.get("https://atlanticcity.pre.tecnalis.com/")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | linkText=INGRESAR | 
    self.driver.find_element(By.LINK_TEXT, "INGRESAR").click()
    # 4 | click | css=.d-xl-block > .btn-casino | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-xl-block > .btn-casino").click()
    # 5 | type | id=username_aside | Nvalencia
    self.driver.find_element(By.ID, "username_aside").send_keys("Nvalencia")
    # 6 | type | id=password_aside | Fari2021
    self.driver.find_element(By.ID, "password_aside").send_keys("Fari2021")
    # 7 | click | id=username_aside | 
    self.driver.find_element(By.ID, "username_aside").click()
    # 8 | click | id=password_aside | 
    self.driver.find_element(By.ID, "password_aside").click()
    # 9 | type | id=password_aside | Fari20210
    self.driver.find_element(By.ID, "password_aside").send_keys("Fari20210")
    # 10 | click | id=login_button_aside | 
    self.driver.find_element(By.ID, "login_button_aside").click()
    # 11 | click | linkText=restablezca su contraseña. | 
    self.driver.find_element(By.LINK_TEXT, "restablezca su contraseña.").click()
    # 12 | click | id=e_mail_forgot | 
    self.driver.find_element(By.ID, "e_mail_forgot").click()
    # 13 | type | id=e_mail_forgot | nvalencia@acity.com.pe
    self.driver.find_element(By.ID, "e_mail_forgot").send_keys("nvalencia@acity.com.pe")
    # 14 | click | id=send_button | 
    self.driver.find_element(By.ID, "send_button").click()
    # 15 | click | css=section > h1 | 
    self.driver.find_element(By.CSS_SELECTOR, "section > h1").click()
    # 16 | close |  | 
    self.driver.close()
  
