# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities



class TestRegisrropaciente():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_registropaciente(self):
        # Test name: Regisrro paciente
        # Step # | name | target | value
        # 1 | open | https://his-qas.tigmed.com.pe/person/patient |
        self.driver.get("https://his-qas.tigmed.com.pe/person/patient")

        # 2 | setWindowSize | 1552x840 |
        self.driver.maximize_window()
        time.sleep(13)
        # 3 | click | linkText=Agregar Paciente |
        self.driver.find_element(By.ID, "username").send_keys("pyarleque")
        time.sleep(2)
        # 4 | mouseOver | linkText=Agregar Paciente |
        self.driver.find_element(By.ID, "password").send_keys("1234567")
        time.sleep(2)
        self.driver.find_element(By.ID, "kc-form-buttons").click()
        time.sleep(5)
        registrarpaciente = self.driver.find_element(By.CSS_SELECTOR, ".nav.px-6")
        a = registrarpaciente.driver.find_element(By.CSS_SELECTOR,"a")
        for butt in  a:
            if butt.text == "Agregar Paciente":
                butt.click()
                time.sleep(15)
        #button = registrarpaciente.driver.find_element(By.LINK_TEXT,"Agregar Paciente").click
        time.sleep(10)
        # 5 | click | css=.row:nth-child(2) > .col-md-4:nth-child(1) > .form-control |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > .col-md-4:nth-child(1) > .form-control").click()
        # 6 | type | css=.ng-dirty | Jorda
        self.driver.find_element(By.CSS_SELECTOR, ".ng-dirty").send_keys("Jorda")
        # 7 | click | css=.col-md-4 > .input-group > .form-control-sm |
        self.driver.find_element(By.CSS_SELECTOR, ".col-md-4 > .input-group > .form-control-sm").click()
        # 8 | type | css=.ng-dirty:nth-child(1) | 74957256
        self.driver.find_element(By.CSS_SELECTOR, ".ng-dirty:nth-child(1)").send_keys("74957256")
        # 9 | click | css=.row:nth-child(2) > .col-md-4:nth-child(2) > .form-control |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) > .col-md-4:nth-child(2) > .form-control").click()
        # 10 | type | css=.col-md-4:nth-child(2) > .ng-dirty | Isla
        self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) > .ng-dirty").send_keys("Isla")
        # 11 | click | css=.row:nth-child(2) .ng-untouched |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) .ng-untouched").click()
        # 12 | type | css=.col-md-4:nth-child(3) > .ng-dirty | Palomino
        self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3) > .ng-dirty").send_keys("Palomino")
        # 13 | click | css=.form-solid-tigmed |
        self.driver.find_element(By.CSS_SELECTOR, ".form-solid-tigmed").click()
        # 14 | type | css=.form-solid-tigmed | 25/02/2003
        self.driver.find_element(By.CSS_SELECTOR, ".form-solid-tigmed").send_keys("25/02/2003")
        # 15 | click | css=.row:nth-child(3) > .col-md-4 > .ng-valid |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) > .col-md-4 > .ng-valid").click()
        # 16 | type | css=.row:nth-child(3) > .col-md-4 > .ng-valid | 984259687
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) > .col-md-4 > .ng-valid").send_keys("984259687")
        # 17 | click | css=.row:nth-child(3) .ng-untouched |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) .ng-untouched").click()
        # 18 | type | css=.row:nth-child(3) .ng-untouched | 984259687
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) .ng-untouched").send_keys("984259687")
        # 19 | click | css=.row:nth-child(4) > .col-md-4:nth-child(1) > .form-control |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > .col-md-4:nth-child(1) > .form-control").click()
        # 20 | type | css=.row:nth-child(4) .ng-dirty | 984259687
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) .ng-dirty").send_keys("984259687")
        # 21 | click | css=.row:nth-child(4) > .col-md-4:nth-child(2) > .form-control |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > .col-md-4:nth-child(2) > .form-control").click()
        # 22 | type | css=.row:nth-child(4) > .col-md-4:nth-child(2) > .form-control | jordan.isla.playstore@gmail.com
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".row:nth-child(4) > .col-md-4:nth-child(2) > .form-control").send_keys(
            "jordan.isla.playstore@gmail.com")
        # 23 | type | css=.ng-select-focused input | Masculino
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys("Masculino")
        # 24 | sendKeys | css=.ng-select-focused input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys(Keys.ENTER)
        # 25 | click | css=.ng-select-focused input |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").click()
        # 26 | type | css=.ng-select-focused input | Soltero
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys("Soltero")
        # 27 | sendKeys | css=.ng-select-focused input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys(Keys.ENTER)
        # 28 | click | css=.row:nth-child(4) > .col-md-4 > .ng-untouched |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > .col-md-4 > .ng-untouched").click()
        # 29 | click | css=.ng-select-focused input |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").click()
        # 30 | type | css=.ng-select-focused input | Catoli
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys("Catoli")
        # 31 | sendKeys | css=.ng-select-focused input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys(Keys.ENTER)
        # 32 | click | css=.ng-select-focused input |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").click()
        # 33 | type | css=.ng-select-focused input | Educacion especial completa
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys("Educacion especial completa")
        # 34 | sendKeys | css=.ng-select-focused input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys(Keys.ENTER)
        # 35 | click | css=.ng-invalid input |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-invalid input").click()
        # 36 | type | css=.ng-invalid input | Mestizo
        self.driver.find_element(By.CSS_SELECTOR, ".ng-invalid input").send_keys("Mestizo")
        # 37 | sendKeys | css=.ng-invalid input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".ng-invalid input").send_keys(Keys.ENTER)
        # 38 | click | css=.ng-input:nth-child(2) > input |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-input:nth-child(2) > input").click()
        # 39 | type | css=.ng-input:nth-child(2) > input | Analista QA
        self.driver.find_element(By.CSS_SELECTOR, ".ng-input:nth-child(2) > input").send_keys("Analista QA")
        # 40 | sendKeys | css=.ng-input:nth-child(2) > input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".ng-input:nth-child(2) > input").send_keys(Keys.ENTER)
        # 41 | click | css=.row:nth-child(7) > .col-md-4 > .form-control |
        self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(7) > .col-md-4 > .form-control").click()
        # 42 | click | css=.ng-input:nth-child(2) > input |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-input:nth-child(2) > input").click()
        # 43 | type | css=.ng-input:nth-child(2) > input | Abogado
        self.driver.find_element(By.CSS_SELECTOR, ".ng-input:nth-child(2) > input").send_keys("Abogado")
        # 44 | sendKeys | css=.ng-input:nth-child(2) > input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".ng-input:nth-child(2) > input").send_keys(Keys.ENTER)
        # 45 | click | css=.ng-select-focused input |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").click()
        # 46 | type | css=.ng-select-focused input | Peru
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys("Peru")
        # 47 | sendKeys | css=.ng-select-focused input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".ng-select-focused input").send_keys(Keys.ENTER)
        # 48 | click | css=.btn-adress |
        self.driver.find_element(By.CSS_SELECTOR, ".btn-adress").click()
        # 49 | click | linkText=Agregar dirección manual |
        self.driver.find_element(By.LINK_TEXT, "Agregar dirección manual").click()
        # 50 | click | css=#countryCode input |
        self.driver.find_element(By.CSS_SELECTOR, "#countryCode input").click()
        # 51 | type | css=#countryCode input | Peru
        self.driver.find_element(By.CSS_SELECTOR, "#countryCode input").send_keys("Peru")
        # 52 | sendKeys | css=#countryCode input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, "#countryCode input").send_keys(Keys.ENTER)
        # 53 | click | css=#regionCode input |
        self.driver.find_element(By.CSS_SELECTOR, "#regionCode input").click()
        # 54 | type | css=#regionCode input | Lima
        self.driver.find_element(By.CSS_SELECTOR, "#regionCode input").send_keys("Lima")
        # 55 | sendKeys | css=#regionCode input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, "#regionCode input").send_keys(Keys.ENTER)
        # 56 | click | css=#provinceCode input |
        self.driver.find_element(By.CSS_SELECTOR, "#provinceCode input").click()
        # 57 | type | css=#provinceCode input | Lima
        self.driver.find_element(By.CSS_SELECTOR, "#provinceCode input").send_keys("Lima")
        # 58 | sendKeys | css=#provinceCode input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, "#provinceCode input").send_keys(Keys.ENTER)
        # 59 | click | css=.ng-input:nth-child(2) > input |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-input:nth-child(2) > input").click()
        # 60 | type | css=.ng-input:nth-child(2) > input | Santa A
        self.driver.find_element(By.CSS_SELECTOR, ".ng-input:nth-child(2) > input").send_keys("Santa A")
        # 61 | sendKeys | css=.ng-input:nth-child(2) > input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".ng-input:nth-child(2) > input").send_keys(Keys.ENTER)
        # 62 | click | id=addressComplete |
        self.driver.find_element(By.ID, "addressComplete").click()
        # 63 | click | css=.modal-footer |
        self.driver.find_element(By.CSS_SELECTOR, ".modal-footer").click()
        # 64 | click | css=.btn-save-rp |
        self.driver.find_element(By.CSS_SELECTOR, ".btn-save-rp").click()
        # 65 | mouseOver | css=.btn-save-rp |
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn-save-rp")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 66 | mouseOut | css=.btn-save-rp |
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_, ".btn-save-rp").click()

test_registropaciente = TestRegisrropaciente