# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCanjePuntos():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_inicioSesin(self):
    self.driver.get("https://atlantic:viQ%5B3UJ*Rk*Q1zC@atlanticcity.pre.tecnalis.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "INGRESAR").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-xl-block > .btn-casino").click()
    self.driver.find_element(By.ID, "username_aside").send_keys("PruebasFide3")
    self.driver.find_element(By.ID, "password_aside").send_keys("Fide2021")
    self.driver.find_element(By.ID, "ojoLogin").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".close-icon:nth-child(1)")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "CREAR CUENTA")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "¿OLVIDÓ SU CONTRASEÑA?")
    assert len(elements) > 0
    element = self.driver.find_element(By.ID, "recordar_pass")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.ID, "login_button_aside").click()
  
  def test_detalleproducto(self):
    self.driver.get("https://atlanticcity.pre.tecnalis.com/casino-online")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, ".material-icons-round").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) > #atlanticCityClubLeft-js").click()
    self.driver.find_element(By.LINK_TEXT, "CANJE DE PUNTOS").click()
    self.driver.find_element(By.CSS_SELECTOR, ".direccion-ubicacion > .pts-negrita").click()
    self.driver.find_element(By.ID, "DireccionID_99954").click()
    elements = self.driver.find_elements(By.LINK_TEXT, "VOLVER")
    assert len(elements) > 0
    self.driver.get("https://atlanticcity.pre.tecnalis.com/ver-detalle-de-producto-personalizado/?detalle-producto=126")
  
  def test_canjeproducto(self):
    self.driver.get("https://atlanticcity.pre.tecnalis.com/ver-detalle-de-producto-personalizado/?detalle-producto=112")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, ".button-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button-minus").click()
    element = self.driver.find_element(By.ID, "check3")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.ID, "radiob4")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.ID, "btnagregar").click()
    self.driver.execute_script("window.scrollTo(0,201)")
    self.driver.find_element(By.LINK_TEXT, "IR AL CARRITO").click()
    self.driver.get("https://atlanticcity.pre.tecnalis.com/carrito-de-compras-personalizado")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-1-confirma").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-2-confirma").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.LINK_TEXT, "IR AL HISTORIAL DE PEDIDOS").click()
    self.driver.get("https://atlanticcity.pre.tecnalis.com/historial-detalle-de-pedidos-personalizado")
    self.driver.find_element(By.CSS_SELECTOR, ".acc-toggler-titulo > .flex-grow-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-12 > .n-pedido").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-2").click()
    self.driver.find_element(By.LINK_TEXT, "Completados").click()
  
  def test_canjeEfectivo(self):
    self.driver.get("https://atlanticcity.pre.tecnalis.com/canjea-tus-puntos")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "Efectivo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".disponible:nth-child(2) .checkmark").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-add-efectivo").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "click-btn2-efectivo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-2-confirma").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-2-confirma").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.LINK_TEXT, "IR AL HISTORIAL DE MIS PEDIDOS").click()
    self.driver.find_element(By.LINK_TEXT, "Completados").click()
    self.driver.find_element(By.CSS_SELECTOR, ".articulo-4446 > .acc-toggler-titulo > .flex-grow-1").click()
  
  def test_canjeEfectivoProducto(self):
    self.driver.get("https://atlanticcity.pre.tecnalis.com/ver-detalle-de-producto-personalizado/?detalle-producto=112")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, ".button-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button-minus").click()
    element = self.driver.find_element(By.ID, "check3")
    if element.is_selected() != True: element.click()
    element = self.driver.find_element(By.ID, "radiob4")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.ID, "btnagregar").click()
    self.driver.execute_script("window.scrollTo(0,201)")
    self.driver.find_element(By.LINK_TEXT, "SEGUIR CANJEANDO").click()
    self.driver.find_element(By.LINK_TEXT, "Efectivo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".disponible:nth-child(2) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-add-efectivo").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "click-btn2-efectivo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button-minus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-1-confirma").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-2-confirma").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.LINK_TEXT, "IR AL HISTORIAL DE MIS PEDIDOS").click()
    self.driver.find_element(By.LINK_TEXT, "Completados").click()
  
  def test_cerrarSesin(self):
    self.driver.get("https://atlanticcity.pre.tecnalis.com/casino-online")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, ".a-button-secondary--dark:nth-child(3)").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".info-montos")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "DEPOSITAR")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "SALDOS  Y  RETIROS")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "PERFIL")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "CONTRASEÑA")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "HISTORIAL")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "CERRAR SESIÓN").click()
    elements = self.driver.find_elements(By.LINK_TEXT, "INGRESAR")
    assert len(elements) > 0
  
