# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.common import InvalidSelectorException, NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLoginingresoHappy():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  def test_loginingresoHappy(self):
    # Test name: Login ingreso Happy
    # Step # | name | target | value
    # 1 | open | https://atlanticcity.pre.tecnalis.com/ |
    self.driver.get("https://atlantic:viQ[3UJ*Rk*Q1zC@atlanticcity.pre.tecnalis.com/")

    self.driver.maximize_window()
    # 3 | click | css=.d-xl-block > .btn-casino |
    # LOGIN
    # Test name: Login ingreso Happy43
    # Step # | name | target | value
    # 1 | open | https://atlanticcity.pre.tecnalis.com/ |

    # 3 | click | css=.d-xl-block > .btn-casino |
    header = self.driver.find_element(By.CSS_SELECTOR, "header")
    buttons = header.find_elements(By.CSS_SELECTOR, "a")
    for button in buttons:
      if button.text == "INGRESAR":
        button.click()
        time.sleep(5)
    # self.driver.find_element(By.CSS_SELECTOR, ".d-xl-block > .btn-casino").click()
    # 4 click to casino online
    wait = WebDriverWait(self.driver, 60)
    target_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".cardDondeVamosCasino > button")))
    target_button.click()
    # time.sleep(10)
    # 5 | type | id=username_aside | Testjordan01
    self.driver.find_element(By.ID, "username_aside").send_keys("Testjordan01")
    self.driver.find_element(By.ID, "password_aside").send_keys("Testjordan01")
    time.sleep(2)
    # 6| click | linkText=INGRESAR |
    self.driver.find_element(By.ID, "login_button_aside").click()
    time.sleep(10)

    #7 Menu

    sodesktop = self.driver.find_element(By.CSS_SELECTOR, ".show-only--desktop")
    menubutton = sodesktop.find_elements(By.CSS_SELECTOR, "a")
    for buttonmen in menubutton:
      if buttonmen.text == "menu":

        buttonmen.click()
        time.sleep(5)

    #8 Promociones

    try:
      #self.driver.find_element(By.ID,"gtm--menu-aside-promociones")
      aside = self.driver.find_element(By.CSS_SELECTOR, ".o-aside.fixed-left")
      prombuttons = aside.find_elements(By.CSS_SELECTOR, "a")
      for buttonmen in prombuttons:
        if buttonmen.text == "PROMOCIONES":
          buttonmen.click()
          time.sleep(10)
    except (Exception, StopIteration) as e:
      print(f"{e}")


    # SELECCIONAR NIVELES DE AD PROMOS 1(2143),2(1385),3(4120),6(1722),7(2275),8(14455),9(4026),0(3337)

    #Seleccioar  ID  DE JUGADOR NIVEL 1
    btn_container = self.driver.find_element(By.ID, "contentModalPlayerOculto")
    btn_oculto = btn_container.find_element(By.CSS_SELECTOR, "button")
    btn_oculto.click()
    # 7 | type | id=idAliraCampo | 850
    self.driver.find_element(By.ID, "idAliraCampo").send_keys("2143")
    # 8 | click | css=button:nth-child(4) |
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 9 | mouseOver | css=.item-prev > button |
    # Bajar cursor
    self.driver.execute_script("window.scrollTo(0,600)")
    self.vars["window_handles"] = self.driver.window_handles

    # SELECCIONAR ID DE JUGADOR NIVEL 2
    btn_container = self.driver.find_element(By.ID, "contentModalPlayerOculto")
    btn_oculto = btn_container.find_element(By.CSS_SELECTOR, "button")
    btn_oculto.click()
    # 7 | type | id=idAliraCampo | 1385
    self.driver.find_element(By.ID, "idAliraCampo").send_keys("1385")
    # 8 | click | css=button:nth-child(4) |
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 9 | mouseOver | css=.item-prev > button |
    # Bajar cursor
    self.driver.execute_script("window.scrollTo(0,600)")
    self.vars["window_handles"] = self.driver.window_handles


    # Seleccioar  ID  DE JUGADOR NIVEL 3
    btn_container = self.driver.find_element(By.ID, "contentModalPlayerOculto")
    btn_oculto = btn_container.find_element(By.CSS_SELECTOR, "button")
    btn_oculto.click()
    # 7 | type | id=idAliraCampo | 4120
    self.driver.find_element(By.ID, "idAliraCampo").send_keys("4120")
    # 8 | click | css=button:nth-child(4) |
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    # 9 | mouseOver | css=.item-prev > button |
    # Bajar cursor
    self.driver.execute_script("window.scrollTo(0,600)")
    self.vars["window_handles"] = self.driver.window_handles
  
test_login_ingreso_happy = TestLoginingresoHappy()