# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver


class TestLoginAlertAuthentication:

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login_alert_authentication(self):
        self.driver.maximize_window()
        self.driver.get("https://atlantic:viQ[3UJ*Rk*Q1zC@atlanticcity.pre.tecnalis.com/")

        time.sleep(30)

        pass


test_login_alert_authentication = TestLoginAlertAuthentication()